name: smartlist
description: Lista de supermercado inteligente com reconhecimento de voz.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  go_router: ^13.2.0

  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1

  flutter_slidable: ^3.1.0
  gap: ^3.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
